trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'myapp'
  dockerRegistryServiceConnection: 'YOUR_DOCKER_REGISTRY_SERVICE_CONNECTION'
  servicePrincipalId: 'YOUR_SERVICE_PRINCIPAL_ID'
  servicePrincipalKey: 'YOUR_SERVICE_PRINCIPAL_KEY'
  tenantId: 'YOUR_TENANT_ID'
  acrName: 'YOUR_ACR_NAME'
  resourceGroup: 'YOUR_RESOURCE_GROUP'
  containerAppName: 'YOUR_CONTAINER_APP_NAME'

stages:
- stage: Test
  jobs:
  - job: RunTests
    displayName: 'Run Tests'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pytest
      displayName: 'Run Unit Tests'

- stage: Build
  dependsOn: Test
  jobs:
  - job: BuildDockerImage
    displayName: 'Build Docker Image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
    - publish: $(Pipeline.Workspace)/images
      artifact: images

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployToContainerApps
    displayName: 'Deploy to Azure Container Apps'
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: images

          - script: |
              az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
              az acr login --name $(acrName)
              az containerapp update --name $(containerAppName) --resource-group $(resourceGroup) --image $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
            displayName: 'Deploy to Azure Container Apps'
